# Generated by Django 3.2.9 on 2021-12-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField()),
                ('fever', models.BooleanField(default=False)),
                ('cough', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('diarrhea', models.BooleanField(default=False)),
                ('tasteless', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CovidPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.patient')),
            ],
        ),
    ]
