# Generated by Django 3.2.9 on 2021-12-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_patient_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CData',
        ),
    ]
