# Generated by Django 3.2.9 on 2021-12-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('covid', models.IntegerField(default=0)),
                ('treatment', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('dead', models.IntegerField(default=0)),
                ('discharged', models.IntegerField(default=0)),
            ],
        ),
    ]
